-- ============================================================
-- NEW TOOLS: goose, cline, kiro, gh-copilot, qoder, trae, kilo-code
-- Append to seed.sql and run on server:
--   sudo docker exec -i atlas-mysql mysql -u root -proot ai_command_atlas < scripts/seed-new-tools.sql
-- ============================================================

SET NAMES utf8mb4;
USE ai_command_atlas;

-- New tools
INSERT INTO tools (slug, name, company, description, description_zh, color, avatar, version, source_type, github_url, docs_url) VALUES
('goose', 'Goose', 'Block / AAIF', 'Open-source AI developer agent by Block (now AAIF). Runs autonomously in your terminal with extensible tooling via MCP, supports any LLM provider, and handles multi-step coding tasks.', 'Block（现 AAIF）开源的 AI 开发者代理。在终端中自主运行，通过 MCP 提供可扩展工具，支持任意 LLM 提供商，可处理多步骤编码任务。', '#00B5B5', 'GS', 'v1.x', 'official', 'https://github.com/aaif-goose/goose', 'https://goose-docs.ai/docs/guides/goose-cli-commands/'),
('cline', 'Cline', 'Cline', 'Open-source AI coding assistant for VS Code. Autonomous multi-step agent with file editing, terminal access, browser control, and MCP server integration.', '开源的 VS Code AI 编码助手。具有文件编辑、终端访问、浏览器控制和 MCP 服务器集成的自主多步骤代理。', '#7C3AED', 'CL', 'v3.x', 'official', 'https://github.com/cline/cline', 'https://docs.cline.bot/cli/cli-reference'),
('kiro', 'Kiro', 'AWS', 'AWS AI IDE with spec-driven development, hooks, and steering rules. Supports CLI chat mode, agent creation, and MCP server integration.', 'AWS AI IDE，具有规格驱动开发、钩子和引导规则。支持 CLI 聊天模式、代理创建和 MCP 服务器集成。', '#FF9900', 'KI', 'v1.x', 'official', 'https://github.com/kirodotdev/Kiro', 'https://kiro.dev/docs/cli/'),
('gh-copilot', 'GitHub Copilot CLI', 'GitHub', 'GitHub Copilot as a gh CLI extension. Explains and suggests shell, Git, and gh commands using natural language. Integrates directly into your terminal workflow.', 'GitHub Copilot 的 gh CLI 扩展。使用自然语言解释和建议 shell、Git 和 gh 命令，直接集成到终端工作流中。', '#6E40C9', 'GH', 'v1.x', 'official', 'https://github.com/github/gh-copilot', 'https://docs.github.com/en/copilot/reference/copilot-cli-reference/cli-command-reference'),
('qoder', 'Qoder', 'Alibaba', 'Alibaba AI coding IDE (VS Code fork) with Quest Mode for spec-driven autonomous task delegation, Repo Wiki for codebase understanding, and Action Flow visualization.', '阿里巴巴 AI 编码 IDE（VS Code 分支），具有用于规格驱动自主任务委托的 Quest 模式、代码库理解的 Repo Wiki 以及 Action Flow 可视化。', '#FF5500', 'QD', 'v1.x', 'official', NULL, 'https://docs.qoder.com/en/cli/command'),
('trae', 'Trae', 'ByteDance', 'ByteDance AI IDE with Builder mode for natural-language project generation, Chat mode for code Q&A, and Cue for inline completions. Supports MCP servers and custom rules.', '字节跳动 AI IDE，具有自然语言项目生成的 Builder 模式、代码问答的 Chat 模式以及行内补全的 Cue 功能。支持 MCP 服务器和自定义规则。', '#5B5BD6', 'TR', 'v1.x', 'official', 'https://github.com/bytedance/trae-agent', 'https://volcengine.com/docs/86677/2227876'),
('kilo-code', 'Kilo Code', 'Kilo', 'VS Code AI coding extension (Roo Code successor). Multi-agent orchestration with specialized modes (Code, Architect, Debug, Plan), 500+ model support via Kilo Gateway, and MCP integration.', 'VS Code AI 编码扩展（Roo Code 的继任者）。具有专业模式（Code、Architect、Debug、Plan）的多代理编排，通过 Kilo Gateway 支持 500+ 模型，以及 MCP 集成。', '#FACC15', 'KC', 'v3.x', 'official', 'https://github.com/Kilo-Org/kilocode', 'https://kilo.ai/docs/code-with-ai/platforms/cli')
ON DUPLICATE KEY UPDATE
  name=VALUES(name), company=VALUES(company), description=VALUES(description),
  description_zh=VALUES(description_zh), color=VALUES(color), github_url=VALUES(github_url), docs_url=VALUES(docs_url);

-- ── Goose commands ──────────────────────────────────────────
SET @gs = (SELECT id FROM tools WHERE slug = 'goose');

INSERT INTO commands (tool_id, slug, name, command_type, category, risk_level, source, description, description_zh, syntax, value_hint, last_checked) VALUES
(@gs, 'session',         'session',          'subcommand', 'Session',    'low',    'official', 'Start an interactive AI session. Default command when no subcommand is given.',                       '启动交互式 AI 会话，未指定子命令时的默认命令。',                              'goose session',                         NULL,                    '2026-06-09'),
(@gs, 'session-resume',  'session -r',       'subcommand', 'Session',    'low',    'official', 'Resume the most recent previous session.',                                                           '恢复最近一次会话。',                                                          'goose session -r',                      NULL,                    '2026-06-09'),
(@gs, 'session-name',    'session -n',       'subcommand', 'Session',    'low',    'official', 'Start a session with a given name for easy retrieval later.',                                        '以指定名称启动会话，便于后续检索。',                                          'goose session -n <name>',               '<name>',                '2026-06-09'),
(@gs, 'session-fork',    'session --fork',   'subcommand', 'Session',    'low',    'official', 'Fork the current session history into a new session.',                                              '将当前会话历史复刻到新会话中。',                                              'goose session --fork',                  NULL,                    '2026-06-09'),
(@gs, 'session-export',  'session export',   'subcommand', 'Session',    'low',    'official', 'Export session history to a file. Supports markdown format via --format.',                         '将会话历史导出到文件，支持通过 --format 指定 markdown 格式。',                 'goose session export [-o <file>]',      NULL,                    '2026-06-09'),
(@gs, 'run',             'run',              'subcommand', 'Session',    'medium', 'official', 'Run a one-shot task from an instruction file or stdin without entering interactive mode.',           '从指令文件或 stdin 运行一次性任务，无需进入交互模式。',                       'goose run [--instructions <file>]',     NULL,                    '2026-06-09'),
(@gs, 'configure',       'configure',        'subcommand', 'Config',     'low',    'official', 'Configure Goose: set LLM provider, API keys, and extensions.',                                     '配置 Goose：设置 LLM 提供商、API 密钥和扩展。',                              'goose configure',                       NULL,                    '2026-06-09'),
(@gs, 'agents',          'agents',           'subcommand', 'Config',     'low',    'official', 'List available agent versions and switch between them.',                                            '列出可用的代理版本并在它们之间切换。',                                        'goose agents',                          NULL,                    '2026-06-09'),
(@gs, 'with-builtin',    '--with-builtin',   'option',     'Session',    'low',    'official', 'Add a built-in extension to the session (e.g. developer, computeruse).',                           '向会话添加内置扩展（例如 developer、computeruse）。',                         'goose session --with-builtin <name>',   '<name>',                '2026-06-09'),
(@gs, 'with-extension',  '--with-extension', 'option',     'Session',    'low',    'official', 'Add a custom stdio extension command to the session.',                                             '向会话添加自定义 stdio 扩展命令。',                                           'goose session --with-extension <cmd>', '<cmd>',                 '2026-06-09'),
(@gs, 'slash-exit',      '/exit',            'slash',      'Session',    'low',    'official', 'Exit the current Goose session.',                                                                  '退出当前 Goose 会话。',                                                       '/exit',                                 NULL,                    '2026-06-09'),
(@gs, 'slash-clear',     '/clear',           'slash',      'Session',    'low',    'official', 'Clear conversation history in the current session.',                                               '清除当前会话的对话历史。',                                                    '/clear',                                NULL,                    '2026-06-09'),
(@gs, 'slash-plan',      '/plan',            'slash',      'Session',    'low',    'official', 'Enter plan mode. Generates a structured plan based on the current conversation.',                  '进入计划模式，根据当前对话生成结构化计划。',                                  '/plan [message]',                       NULL,                    '2026-06-09'),
(@gs, 'slash-mode',      '/mode',            'slash',      'Permission', 'medium', 'official', 'Switch agent operating mode: auto (runs autonomously), approve (confirms actions), or chat.',      '切换代理操作模式：auto（自主运行）、approve（确认操作）或 chat。',            '/mode <auto|approve|chat>',             '<auto|approve|chat>',   '2026-06-09'),
(@gs, 'slash-compact',   '/compact',         'slash',      'Session',    'low',    'official', 'Compress conversation history to reduce context window usage.',                                    '压缩对话历史以减少上下文窗口使用量。',                                        '/compact',                              NULL,                    '2026-06-09'),
(@gs, 'slash-recipe',    '/recipe',          'slash',      'Config',     'low',    'official', 'Generate a reusable recipe (.yaml) from the current session.',                                    '从当前会话生成可复用的 recipe（.yaml 文件）。',                               '/recipe [filepath]',                    NULL,                    '2026-06-09'),
(@gs, 'slash-builtin',   '/builtin',         'slash',      'Config',     'low',    'official', 'Add a built-in extension to the current running session.',                                        '向当前运行的会话添加内置扩展。',                                              '/builtin <name>',                       NULL,                    '2026-06-09'),
(@gs, 'goosehints',      '.goosehints',      'config',     'Config',     'low',    'official', 'Project instructions file loaded at session start. Similar to CLAUDE.md — guides Goose behavior.', '会话启动时加载的项目指令文件，类似于 CLAUDE.md，用于引导 Goose 行为。',      '.goosehints',                           NULL,                    '2026-06-09')
ON DUPLICATE KEY UPDATE description=VALUES(description), description_zh=VALUES(description_zh), syntax=VALUES(syntax), last_checked=VALUES(last_checked);

-- ── Cline commands ──────────────────────────────────────────
SET @cl = (SELECT id FROM tools WHERE slug = 'cline');

INSERT INTO commands (tool_id, slug, name, command_type, category, risk_level, source, description, description_zh, syntax, value_hint, last_checked) VALUES
(@cl, 'newtask',         '/newtask',         'slash',      'Session',    'low',    'official', 'Start a new task in a fresh context, preserving conversation history.',                            '在新上下文中开始新任务，同时保留对话历史。',                                  '/newtask',                              NULL,                    '2026-06-09'),
(@cl, 'newrule',         '/newrule',         'slash',      'Config',     'low',    'official', 'Create a new .clinerules file to set project-specific coding standards and guidelines.',           '创建新的 .clinerules 文件，设置项目特定的编码标准和指南。',                   '/newrule',                              NULL,                    '2026-06-09'),
(@cl, 'deep-planning',   '/deep-planning',   'slash',      'Session',    'low',    'official', 'Four-step structured implementation planning. Generates an implementation_plan.md artifact.',      '四步结构化实现规划，生成 implementation_plan.md 工件。',                      '/deep-planning',                        NULL,                    '2026-06-09'),
(@cl, 'smol',            '/smol',            'slash',      'Session',    'low',    'official', 'Enable minimal output mode — Cline provides concise responses.',                                  '启用最小输出模式，Cline 提供简洁响应。',                                      '/smol',                                 NULL,                    '2026-06-09'),
(@cl, 'reportbug',       '/reportbug',       'slash',      'Session',    'low',    'official', 'Report a bug with the current session context automatically included.',                            '报告 bug，自动包含当前会话上下文。',                                          '/reportbug',                            NULL,                    '2026-06-09'),
(@cl, 'mcp-prompt',      '/mcp:<srv>:<pmt>', 'slash',      'MCP',        'low',    'official', 'Invoke a prompt from a connected MCP server.',                                                    '调用已连接 MCP 服务器的 prompt。',                                            '/mcp:<server>:<prompt>',                NULL,                    '2026-06-09'),
(@cl, 'clinerules',      '.clinerules',      'config',     'Config',     'low',    'official', 'Project rules directory. Files here define coding standards injected into every task.',            '项目规则目录，其中的文件定义注入每个任务的编码标准。',                        '.clinerules/',                          NULL,                    '2026-06-09'),
(@cl, 'plan-mode',       'Plan mode',        'config',     'Permission', 'low',    'official', 'Read-only planning mode. Cline proposes changes but does not execute them without approval.',     '只读规划模式，Cline 提出变更但未经批准不执行。',                              'Plan mode (toggle in UI)',               NULL,                    '2026-06-09'),
(@cl, 'act-mode',        'Act mode',         'config',     'Permission', 'medium', 'official', 'Autonomous execution mode. Cline reads, writes, and runs commands to complete the task.',        '自主执行模式，Cline 读取、写入和运行命令以完成任务。',                        'Act mode (toggle in UI)',               NULL,                    '2026-06-09')
ON DUPLICATE KEY UPDATE description=VALUES(description), description_zh=VALUES(description_zh), syntax=VALUES(syntax), last_checked=VALUES(last_checked);

-- ── Kiro commands ────────────────────────────────────────────
SET @ki = (SELECT id FROM tools WHERE slug = 'kiro');

INSERT INTO commands (tool_id, slug, name, command_type, category, risk_level, source, description, description_zh, syntax, value_hint, last_checked) VALUES
(@ki, 'chat',            'chat',             'subcommand', 'Session',    'low',    'official', 'Start an interactive chat session with the AI.',                                                   '启动与 AI 的交互式聊天会话。',                                                'kiro-cli chat [message]',               NULL,                    '2026-06-09'),
(@ki, 'chat-no-inter',   'chat --no-interactive','subcommand','Session', 'medium', 'official', 'Run a single chat message non-interactively (pipe-friendly).',                                   '以非交互方式运行单条聊天消息（支持管道）。',                                  'kiro-cli chat --no-interactive --trust-all-tools',NULL,          '2026-06-09'),
(@ki, 'chat-resume',     'chat --resume',    'subcommand', 'Session',    'low',    'official', 'Resume the most recent chat session.',                                                            '恢复最近的聊天会话。',                                                        'kiro-cli chat --resume',                NULL,                    '2026-06-09'),
(@ki, 'login',           'login',            'subcommand', 'Config',     'low',    'official', 'Authenticate with AWS Builder ID or Identity Center.',                                            '使用 AWS Builder ID 或 Identity Center 进行身份验证。',                      'kiro-cli login',                        NULL,                    '2026-06-09'),
(@ki, 'login-social',    'login --social',   'subcommand', 'Config',     'low',    'official', 'Login using a social provider (Google or GitHub).',                                              '使用社交账号（Google 或 GitHub）登录。',                                      'kiro-cli login --social <google|github>','<google|github>',      '2026-06-09'),
(@ki, 'agent-create',    'agent create',     'subcommand', 'Config',     'low',    'official', 'Create a new named agent configuration.',                                                         '创建新的命名代理配置。',                                                      'kiro-cli agent create <name>',          '<name>',                '2026-06-09'),
(@ki, 'agent-edit',      'agent edit',       'subcommand', 'Config',     'low',    'official', 'Edit an existing agent configuration.',                                                           '编辑现有的代理配置。',                                                        'kiro-cli agent edit <name>',            '<name>',                '2026-06-09'),
(@ki, 'settings-list',   'settings list',    'subcommand', 'Config',     'low',    'official', 'List all current Kiro settings.',                                                                 '列出所有当前 Kiro 设置。',                                                    'kiro-cli settings list [--all]',        NULL,                    '2026-06-09'),
(@ki, 'settings-set',    'settings set',     'subcommand', 'Config',     'low',    'official', 'Set a configuration value (e.g. telemetry.enabled, model).',                                    '设置配置值（例如 telemetry.enabled、model）。',                               'kiro-cli settings <key> <value>',       '<key> <value>',         '2026-06-09'),
(@ki, 'inline',          'inline',           'subcommand', 'Config',     'low',    'official', 'Enable, disable, or check status of inline ghost-text completions.',                             '启用、禁用或检查行内幽灵文本补全的状态。',                                    'kiro-cli inline <enable|disable|status>','<enable|disable|status>','2026-06-09'),
(@ki, 'diagnostics',     'diagnostics',      'subcommand', 'Config',     'low',    'official', 'Run diagnostic tests to verify Kiro setup and connectivity.',                                    '运行诊断测试以验证 Kiro 设置和连接性。',                                      'kiro-cli diagnostics',                  NULL,                    '2026-06-09'),
(@ki, 'trust-all-tools', '--trust-all-tools','flag',       'Permission', 'high',   'official', 'Auto-approve all tool executions without confirmation prompts.',                                  '无需确认提示，自动批准所有工具执行。',                                        '--trust-all-tools',                     NULL,                    '2026-06-09'),
(@ki, 'slash-context',   '/context',         'slash',      'Session',    'low',    'official', 'Manage context files and view context window usage.',                                             '管理上下文文件并查看上下文窗口使用情况。',                                    '/context',                              NULL,                    '2026-06-09'),
(@ki, 'slash-tools',     '/tools',           'slash',      'Permission', 'low',    'official', 'View and manage tool permissions for the current session.',                                       '查看和管理当前会话的工具权限。',                                              '/tools',                                NULL,                    '2026-06-09'),
(@ki, 'slash-mcp',       '/mcp',             'slash',      'MCP',        'low',    'official', 'Display currently active MCP servers.',                                                           '显示当前激活的 MCP 服务器。',                                                 '/mcp',                                  NULL,                    '2026-06-09'),
(@ki, 'slash-hooks',     '/hooks',           'slash',      'Config',     'low',    'official', 'Display activated context hooks (file change triggers).',                                        '显示已激活的上下文钩子（文件变更触发器）。',                                  '/hooks',                                NULL,                    '2026-06-09'),
(@ki, 'slash-prompts',   '/prompts',         'slash',      'MCP',        'low',    'official', 'View prompt templates provided by connected MCP servers.',                                       '查看已连接 MCP 服务器提供的 prompt 模板。',                                   '/prompts',                              NULL,                    '2026-06-09'),
(@ki, 'spec',            'Spec',             'config',     'Config',     'low',    'official', 'Spec file for spec-driven development. Defines requirements, design, and tasks for a feature.',   '规格驱动开发的规格文件，定义功能的需求、设计和任务。',                        '.kiro/specs/<feature>/',                NULL,                    '2026-06-09'),
(@ki, 'steering',        'Steering',         'config',     'Config',     'low',    'official', 'Steering rules files that guide AI behavior. Always-on or file-matched rules.',                  '引导 AI 行为的引导规则文件，支持始终开启或文件匹配规则。',                    '.kiro/steering/*.md',                   NULL,                    '2026-06-09')
ON DUPLICATE KEY UPDATE description=VALUES(description), description_zh=VALUES(description_zh), syntax=VALUES(syntax), last_checked=VALUES(last_checked);

-- ── GitHub Copilot CLI commands ──────────────────────────────
SET @gh = (SELECT id FROM tools WHERE slug = 'gh-copilot');

INSERT INTO commands (tool_id, slug, name, command_type, category, risk_level, source, description, description_zh, syntax, value_hint, last_checked) VALUES
(@gh, 'suggest',         'suggest',          'subcommand', 'Session',    'low',    'official', 'Suggest a shell, Git, or gh command based on a natural language description.',                    '根据自然语言描述建议 shell、Git 或 gh 命令。',                               'gh copilot suggest [query]',            NULL,                    '2026-06-09'),
(@gh, 'explain',         'explain',          'subcommand', 'Session',    'low',    'official', 'Explain what a given shell command does in plain language.',                                       '用通俗语言解释给定 shell 命令的作用。',                                       'gh copilot explain [command]',          NULL,                    '2026-06-09'),
(@gh, 'alias',           'alias',            'subcommand', 'Config',     'low',    'official', 'Generate shell alias script. Adds ghcs (suggest) and ghce (explain) shortcuts to your shell.',   '生成 shell 别名脚本，向 shell 添加 ghcs（suggest）和 ghce（explain）快捷方式。','gh copilot alias',                    NULL,                    '2026-06-09'),
(@gh, 'config',          'config',           'subcommand', 'Config',     'low',    'official', 'Configure Copilot CLI options, including command execution confirmation behavior.',                '配置 Copilot CLI 选项，包括命令执行确认行为。',                               'gh copilot config',                     NULL,                    '2026-06-09'),
(@gh, 'target-shell',    '-t / --target',    'option',     'Session',    'low',    'official', 'Specify the command target type: shell, gh, or git.',                                            '指定命令目标类型：shell、gh 或 git。',                                        'gh copilot suggest -t <type>',          '<shell|gh|git>',        '2026-06-09'),
(@gh, 'completion',      'completion',       'subcommand', 'Config',     'low',    'official', 'Generate shell completion scripts for bash, zsh, or fish.',                                       '为 bash、zsh 或 fish 生成 shell 补全脚本。',                                  'gh copilot completion <shell>',         '<bash|zsh|fish>',       '2026-06-09')
ON DUPLICATE KEY UPDATE description=VALUES(description), description_zh=VALUES(description_zh), syntax=VALUES(syntax), last_checked=VALUES(last_checked);

-- ── Qoder commands ───────────────────────────────────────────
SET @qd = (SELECT id FROM tools WHERE slug = 'qoder');

INSERT INTO commands (tool_id, slug, name, command_type, category, risk_level, source, description, description_zh, syntax, value_hint, last_checked) VALUES
(@qd, 'quest',           'quest',            'subcommand', 'Session',    'medium', 'official', 'Quest mode: delegate a spec-driven coding task. Qoder autonomously plans, codes, and verifies.', 'Quest 模式：委托规格驱动的编码任务，Qoder 自主规划、编码和验��。',           'qoder quest --spec "<description>"',    NULL,                    '2026-06-09'),
(@qd, 'quest-spec',      '--spec',           'option',     'Session',    'medium', 'official', 'Natural language specification for the Quest task to be completed.',                             'Quest 任务的自然语言规格描述。',                                              '--spec "<task description>"',           '<description>',         '2026-06-09'),
(@qd, 'agent-mode',      'Agent mode',       'config',     'Session',    'low',    'official', 'Conversational agent mode for interactive coding assistance.',                                    '用于交互式编码辅助的对话式代理模式。',                                        'Agent mode (IDE)',                       NULL,                    '2026-06-09'),
(@qd, 'repo-wiki',       'Repo Wiki',        'config',     'Config',     'low',    'official', 'Continuously synced project knowledge base. Keeps AI aware of code structure and implementation.','持续同步的项目知识库，使 AI 了解代码结构和实现细节。',                      'Repo Wiki (IDE)',                        NULL,                    '2026-06-09'),
(@qd, 'action-flow',     'Action Flow',      'config',     'Session',    'low',    'official', 'Visual panel showing agent planning steps and execution progress.',                               '显示代理规划步骤和执行进度的可视化面板。',                                    'Action Flow (IDE)',                      NULL,                    '2026-06-09')
ON DUPLICATE KEY UPDATE description=VALUES(description), description_zh=VALUES(description_zh), syntax=VALUES(syntax), last_checked=VALUES(last_checked);

-- ── Trae commands ────────────────────────────────────────────
SET @tr = (SELECT id FROM tools WHERE slug = 'trae');

INSERT INTO commands (tool_id, slug, name, command_type, category, risk_level, source, description, description_zh, syntax, value_hint, last_checked) VALUES
(@tr, 'builder-mode',    'Builder mode',     'config',     'Session',    'medium', 'official', 'Generate a full project from a natural language description. Shows change preview before applying.','从自然语言描述生成完整项目，在应用前显示变更预览。',                         'Builder mode (IDE)',                    NULL,                    '2026-06-09'),
(@tr, 'chat-mode',       'Chat mode',        'config',     'Session',    'low',    'official', 'Side chat panel for code Q&A, explanations, and targeted edits.',                                '用于代码问答、解释和定向编辑的侧边栏聊天面板。',                              'Chat mode (IDE)',                       NULL,                    '2026-06-09'),
(@tr, 'inline-chat',     'Inline chat',      'config',     'Session',    'low',    'official', 'In-editor inline chat for context-aware code edits and questions.',                              '编辑器内行内聊天，用于上下文感知的代码编辑和提问。',                          'Inline chat (IDE)',                     NULL,                    '2026-06-09'),
(@tr, 'cue',             'Cue',              'config',     'Session',    'low',    'official', 'AI inline code completion. Suggests code as you type.',                                          'AI 行内代码补全，在输入时建议代码。',                                         'Cue (IDE)',                             NULL,                    '2026-06-09'),
(@tr, 'project-rules',   '.trae/rules/',     'config',     'Config',     'low',    'official', 'Project rules directory. Markdown files guide AI behavior for the project.',                     '项目规则目录，Markdown 文件引导项目的 AI 行为。',                             '.trae/rules/project_rules.md',         NULL,                    '2026-06-09'),
(@tr, 'rule-ref',        '#rulename',        'slash',      'Config',     'low',    'official', 'Reference a rule file in conversation by name using the # prefix.',                             '在对话中使用 # 前缀按名称引用规则文件。',                                     '#<rulename>',                           '<rulename>',            '2026-06-09'),
(@tr, 'slash-specify',   '/specify',         'slash',      'Session',    'low',    'official', 'Define requirements specification for the current task.',                                         '为当前任务定义需求规格。',                                                    '/specify',                              NULL,                    '2026-06-09'),
(@tr, 'slash-plan',      '/plan',            'slash',      'Session',    'low',    'official', 'Choose an architectural approach for the current task.',                                          '为当前任务选择架构方案。',                                                    '/plan',                                 NULL,                    '2026-06-09'),
(@tr, 'slash-tasks',     '/tasks',           'slash',      'Session',    'low',    'official', 'Break down the current task into implementation subtasks.',                                       '将当前任务分解为实现子任务。',                                                '/tasks',                                NULL,                    '2026-06-09'),
(@tr, 'slash-implement', '/implement',       'slash',      'Session',    'medium', 'official', 'Execute the planned tasks and implement the code changes.',                                       '执行计划的任务并实现代码变更。',                                              '/implement',                            NULL,                    '2026-06-09')
ON DUPLICATE KEY UPDATE description=VALUES(description), description_zh=VALUES(description_zh), syntax=VALUES(syntax), last_checked=VALUES(last_checked);

-- ── Kilo Code commands ───────────────────────────────────────
SET @kc = (SELECT id FROM tools WHERE slug = 'kilo-code');

INSERT INTO commands (tool_id, slug, name, command_type, category, risk_level, source, description, description_zh, syntax, value_hint, last_checked) VALUES
(@kc, 'code-mode',       'Code mode',        'config',     'Session',    'medium', 'official', 'Primary autonomous coding mode. Kilo reads, writes, and executes to implement features.',         '主要的自主编码模式，Kilo 读取、写入和执行以实现功能。',                       'Code mode (IDE)',                       NULL,                    '2026-06-09'),
(@kc, 'architect-mode',  'Architect mode',   'config',     'Session',    'low',    'official', 'High-level planning and architecture design mode. Focuses on structure without writing code.',    '高级规划和架构设计模式，专注于结构设计而不编写代码。',                        'Architect mode (IDE)',                  NULL,                    '2026-06-09'),
(@kc, 'debug-mode',      'Debug mode',       'config',     'Session',    'low',    'official', 'Specialized debugging mode. Analyzes errors and suggests targeted fixes.',                       '专业调试模式，分析错误并建议针对性修复。',                                    'Debug mode (IDE)',                      NULL,                    '2026-06-09'),
(@kc, 'plan-mode',       'Plan mode',        'config',     'Session',    'low',    'official', 'Task planning mode. Creates structured implementation plans without making changes.',             '任务规划模式，创建结构化实现计划而不进行变更。',                              'Plan mode (IDE)',                       NULL,                    '2026-06-09'),
(@kc, 'slash-help',      '/help',            'slash',      'Session',    'low',    'official', 'Show available commands and Kilo Code usage information.',                                       '显示可用命令和 Kilo Code 使用信息。',                                         '/help',                                 NULL,                    '2026-06-09'),
(@kc, 'slash-model',     '/model',           'slash',      'Model',      'low',    'official', 'Switch the AI model used in the current session.',                                              '切换当前会话使用的 AI 模型。',                                                '/model',                                NULL,                    '2026-06-09'),
(@kc, 'slash-compact',   '/compact',         'slash',      'Session',    'low',    'official', 'Compress conversation history to free up context window tokens.',                                '压缩对话历史以释放上下文窗口令牌。',                                          '/compact',                              NULL,                    '2026-06-09'),
(@kc, 'slash-sessions',  '/sessions',        'slash',      'Session',    'low',    'official', 'Manage and switch between saved sessions.',                                                      '管理和切换已保存的会话。',                                                    '/sessions',                             NULL,                    '2026-06-09'),
(@kc, 'slash-agents',    '/agents',          'slash',      'Config',     'low',    'official', 'Open the agent mode selector to switch between Code, Architect, Debug, Plan.',                  '打开代理模式选择器，在 Code、Architect、Debug、Plan 之间切换。',               '/agents',                               NULL,                    '2026-06-09'),
(@kc, 'kilo-rules',      '.kilo/rules/',     'config',     'Config',     'low',    'official', 'Project rules directory. Markdown files define coding standards injected into every session.',   '项目规则目录，Markdown 文件定义注入每次会话的编码标准。',                     '.kilo/rules/',                          NULL,                    '2026-06-09'),
(@kc, 'gateway-model',   'Kilo Gateway',     'config',     'Model',      'low',    'official', 'Access 500+ AI models through Kilo Gateway with zero markup over provider pricing.',            '通过 Kilo Gateway 以提供商原价访问 500+ AI 模型，零溢价。',                   'Kilo Gateway (Settings)',               NULL,                    '2026-06-09'),
(@kc, 'mcp-server',      'MCP server',       'config',     'MCP',        'medium', 'official', 'Connect external MCP tool servers to extend Kilo Code capabilities.',                           '连接外部 MCP 工具服务器以扩展 Kilo Code 功能。',                             'MCP server (Settings)',                 NULL,                    '2026-06-09')
ON DUPLICATE KEY UPDATE description=VALUES(description), description_zh=VALUES(description_zh), syntax=VALUES(syntax), last_checked=VALUES(last_checked);
